config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resource :otp, only: %i[new create]

  resources :users, only: %i[index edit update show destroy]
  resources :bookings do
    collection do
      get :check_availability
    end
    member do
      patch :check_in
      patch :check_out
      get :bill
    end
  end
  resources :rooms
  resources :room_types
  resources :invoices
  # resource :verification, only: [:new, :create/]
  get 'admin', to: 'home#admin'
  get 'staff', to: 'home#staff'
  get 'customer', to: 'home#customer'
  get 'logout', to: 'home#destroy'
  root 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.admin?
      redirect_to new_otp_path
    elsif current_user.staff?
      redirect_to new_otp_path
    else
      redirect_to new_otp_path
    end
  end

  def destroy
    (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    # set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    # respond_to_on_destroy
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/admin.html.erb
<h1>Welcome To Admin Pannel</h1>
<% if current_user.admin?%>
    <p>Hello, <%= current_user.name %>!</p>
<%end%>
<div class="row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">BOOKING</h5>
        <p class="card-text">Do Booking And Check Guest Check_In And Check_Out.</p>
        <a class="btn btn-primary" <%=link_to "Booking",bookings_path  %></a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">USERS And STAFF</h5>
        <p class="card-text">Manage users and staff.</p>
        <a class="btn btn-primary" <%=link_to "Users",users_path  %></a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">ROOM</h5>
        <p class="card-text">Manage the rooms</p>
        <a class="btn btn-primary" <%=link_to "Room",rooms_path  %></a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">ROOM TYPES</h5>
        <p class="card-text">Manage rooms types and their rating.</p>
        <a class="btn btn-primary" <%=link_to "Room Type",room_types_path  %></a>
      </div>
    </div>
  </div>
</div>
<br>
<a class="btn btn-warning"<%= link_to 'logout',logout_path %>

app/views/home/customer.html.erb
<!DOCTYPE html>
<html>
  <head>
  <ul class="nav nav-pills nav-fill">
  <li class="nav-item">
   <a class="nav-link active" aria-current="page <%= link_to 'Home',customer_path %></a>
  </li>
  <li class="nav-item">
    <% if current_user.customer? %>
        <a class="nav-link"<%= link_to 'Booking',new_booking_path %></a>
    <% end %>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">Profile</a>
    <ul class="dropdown-menu">
      <li>
        <% if signed_in? %>
          <a class="nav-link "<%= link_to 'Logout',logout_path %></a>
        <% end %>
      </li>
       <a class="nav-link "<%= link_to 'Profile',user_path(current_user) %></a>
      </li>
    </ul>
  </li>

  </ul>
  </head>

  <br><br><br>

  <body>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <%= image_tag("single.jpeg")%>
      <div class="card-body">
        <h5 class="card-title">Single Room</h5>
        <p class="card-text">Price: 700 </p>
        <% if current_user.customer? %>
            <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag("twin.jpeg")%>
       <div class="card-body">
        <h5 class="card-title">Twin Or Double Room</h5>
        <p class="card-text">Price: 1500 </p>
        <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag("queen.jpeg")%>
       <div class="card-body">
        <h5 class="card-title">Queen Rooms </h5>
        <p class="card-text">Price: 2000 </p>
        <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag("tripleroom.jpeg")%>
       <div class="card-body">
        <h5 class="card-title">Triple Bed Rooms </h5>
        <p class="card-text">Price: 2800 </p>
        <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag("studio.jpeg")%>
       <div class="card-body">
        <h5 class="card-title">studio Rooms </h5>
        <p class="card-text">Price: 2500 </p>
        <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag("suite.jpeg")%>
       <div class="card-body">
        <h5 class="card-title">Suites </h5>
        <p class="card-text">Price: 5000 </p>
        <a class="btn btn-primary"<%=link_to 'Book Now',new_booking_path %></>
      </div>
    </div>
  </div>
</div>

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active d-block w-100">
      <%= image_tag("single.jpeg")%>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
  </body>
</html>

app/views/home/staff.html.erb
<h1>Welcome To Staff Pannel</h1>
<% if current_user.staff?%>
    <p>Hello, <%= current_user.name %>!</p>
<%end%>
<div class="row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">BOOKING</h5>
        <p class="card-text">Do Booking And Check Guest Check_In And Check_Out.</p>
        <a class="btn btn-primary" <%=link_to "Booking",bookings_path  %></a>
      </div>
    </div>
  </div>

  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Available Rooms</h5>
        <p class="card-text">Room that are available for booking.</p>
        <a class="btn btn-primary" <%=link_to "Available Room",check_availability_bookings_path  %></a>
      </div>
    </div>
  </div>

  
</div>
<br>
<a class="btn btn-warning"<%= link_to 'logout',logout_path %>