config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resource :otp, only: %i[new create]

  resources :users, only: %i[index edit update show destroy]
  resources :bookings do
    collection do
      get :check_availability
    end
    member do
      patch :check_in
      patch :check_out
      get :bill
    end
  end
  resources :rooms
  resources :room_types
  resources :invoices
  # resource :verification, only: [:new, :create/]
  get 'admin', to: 'home#admin'
  get 'staff', to: 'home#staff'
  get 'customer', to: 'home#customer'
  get 'logout', to: 'home#destroy'
  root 'home#index'
end

app/controllers/room_types_controller.rb
# frozen_string_literal: true

class RoomTypesController < ApplicationController
  before_action :authorize_admin
  before_action :set_room_type, only: %i[show edit update destroy]

  def index
    @room_types = RoomType.all
  end

  def show; end

  def new
    @room_type = RoomType.new
  end

  def create
    # debugger
    @room_type = RoomType.new(room_type_params)
    if @room_type.save
      redirect_to room_types_path, notice: 'Room type was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room_type.update(room_type_params)
      redirect_to room_types_path, notice: 'Room type was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room_type.destroy
    redirect_to room_types_path, notice: 'Room type was successfully destroyed.'
  end

  private

  def set_room_type
    @room_type = RoomType.find(params[:id])
  end

  def room_type_params
    params.require(:room_type).permit(:name, :rate)
  end
end

app/helpers/room_types_helper.rb
# frozen_string_literal: true

module RoomTypesHelper
end

app/views/room_types/edit.html.erb
<h2><%= action_name.capitalize %> Room Type </h2>
<hr>

<%= form_with(model: @room_type, local:true) do |form| %>
    <% if @room_type.errors.any? %>
    <div id="error_explantion">
        <h2><%= pluralize(@room_type.errors.count, "error") %> prohibited this room type from being saved:</h2>

        <ul>
        <% @room_type.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

   <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
   </div>

   <div class="mb-3">
    <%= form.label :rate %>
    <%= form.number_field :rate, step: :any %>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>

<a class="btn btn-warning"<%= link_to 'Back', room_types_path %></a>

app/views/room_types/index.html.erb
<h1>Room Types</h1>

<a class="btn btn-warning"<%= link_to "New Room Type", new_room_type_path %></a>

<table class="table table-hover table-light">
    <thead>
    <tr>
        <th>Name</th>
        <th>Rate</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @room_types.each do |room_type| %>
        <tr>
        <td><%= room_type.name %></td>
        <td><%=  room_type.rate %></td>
        <td><a class="btn btn-warning"<%= link_to 'show',room_type_path(room_type.id) %></a></td>
        <td><a class="btn btn-warning"<%= link_to 'edit', edit_room_type_path(room_type.id) %></a></td>
        <td><a class="btn btn-warning"<%= link_to 'delete',room_type_path(room_type.id), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %></a></td>
        </tr>
    <% end %>
    </tbody>
</table>
<a class="btn btn-warning" <%= link_to 'Back', admin_path %></a>

app/views/room_types/new.html.erb
<h2><%= action_name.capitalize %> Room Type </h2>
<hr>

<%= form_with(model: @room_type, local:true) do |form| %>
    <% if @room_type.errors.any? %>
    <div id="error_explantion">
        <h2><%= pluralize(@room_type.errors.count, "error") %> prohibited this room type from being saved:</h2>

        <ul>
        <% @room_type.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

   <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
   </div>

   <div class="mb-3">
    <%= form.label :rate %>
    <%= form.number_field :rate, step: :any %>
   </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>

<a class="btn btn-warning"<%= link_to 'Back', room_types_path %></a>

app/views/room_types/show.html.erb
<h1>Room Type Details</h1>

<p>
  <strong>Name:</strong>
  <%= @room_type.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @room_type.rate %>
</p>

<a class="btn btn-warning"<%= link_to 'Edit', edit_room_type_path(@room_type) %></a> |
<a class="btn btn-warning"<%= link_to 'Back', room_types_path %>