config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resource :otp, only: %i[new create]

  resources :users, only: %i[index edit update show destroy]
  resources :bookings do
    collection do
      get :check_availability
    end
    member do
      patch :check_in
      patch :check_out
      get :bill
    end
  end
  resources :rooms
  resources :room_types
  resources :invoices
  # resource :verification, only: [:new, :create/]
  get 'admin', to: 'home#admin'
  get 'staff', to: 'home#staff'
  get 'customer', to: 'home#customer'
  get 'logout', to: 'home#destroy'
  root 'home#index'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :room_type
  has_many :bookings

  validates :room_number, presence: true, uniqueness: true
  validates :status, presence: true

  STATUSES = %w[clean occupied maintenace].freeze

  def available?
    status == clean
  end
end

app/models/room_type.rb
# frozen_string_literal: true

class RoomType < ApplicationRecord
  has_many :rooms
  has_many :bookings, through: :rooms

  validates :name, presence: true
  validates :rate, presence: true
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :authorize_admin
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.all
  end

  def show; end

  def new
    @room = Room.new
    @room_types = RoomType.all
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def edit
    @room_types = RoomType.all
  end

  def update
    if @room.update(room_params)
      redirect_to rooms_path, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:room_number, :room_type_id, :status)
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1><%= action_name.capitalize %> Room</h1>

<%= form_with(model: @room, local: true) do |form| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :room_number %>
    <%= form.text_field :room_number %>
  </div>

  <div class="mb-3 ">
    <%= form.label :room_id %>
    <%= form.collection_select :room_type_id, @room_types, :id, :name %>
  </div>

  <div class="mb-3">
    <%= form.label :status %>
    <%= form.select :status, Room::STATUSES %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>

<a class="btn btn-warning"<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Room</h1>

<a class="btn btn-warning"<%= link_to 'New Room', new_room_path %></a>

<table class="table table-hover table-light">
    <thead>
    <tr>
        <th>Room Number</th>
        <th>Room</th>
        <th>Status</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @rooms.each do |room| %>
        <tr>
        <td><%= room.room_number %></td>
        <td><%= room.room_type.name %></td>
        <td><%= room.status %></td>
        <td><a class="btn btn-warning"<%= link_to 'show',room_path(room.id) %></a></td>
        <td><a class="btn btn-warning"<%= link_to 'edit', edit_room_path(room.id) %></a></td>
        <td><a class="btn btn-warning"<%= link_to 'delete',room_path(room.id), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %></a></td>
        </tr>
    <% end %>
    </tbody>
</table>
<a class="btn btn-warning" <%= link_to 'Back', admin_path %></a>

app/views/rooms/new.html.erb
<h1><%= action_name.capitalize %> Room</h1>

<%= form_with(model: @room, local: true) do |form| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :room_number %>
    <%= form.text_field :room_number %>
  </div>

  <div class="mb-3 ">
    <%= form.label :room_id %>
    <%= form.collection_select :room_type_id, @room_types, :id, :name %>
  </div>

  <div class="mb-3">
    <%= form.label :status %>
    <%= form.select :status, Room::STATUSES %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>

<a class="btn btn-warning"<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<h2>Room Details</h2>

<p>
  <strong>Room Number:</strong>
  <%= @room.room_number %>
</p>


<p>
  <strong>Room Type:</strong>
  <%= @room.room_type.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<a class="btn btn-warning"<%= link_to 'Edit', edit_room_path(@room) %> |
<a class="btn btn-warning"<%= link_to 'Back', rooms_path %>